# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: ssh
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: vim
# Aliases allow you to create nicknames for gh commands
aliases:
    a: f adds
    b: f branches
    l: f logs
    t: f tags
    prs: f prs
    clone: repo clone
    prco: pr checkout
version: "1"
